/** Client-side mirrors of attribute value code / SKU segment rules (see app/utils). */

const AUTO_VALUE_CODE_RE = /^V[A-F0-9]{12}$/;
const SKU_SEGMENT_MAX = 5;

export function normalizeAttributeCodeClient(raw: string): string {
  const s = (raw || '').trim();
  if (!s) {
    return '';
  }
  const parts: string[] = [];
  for (const ch of s) {
    if (/[A-Za-z0-9]/.test(ch)) {
      parts.push(ch.toUpperCase());
    } else if (/[-_ ]/.test(ch)) {
      parts.push('-');
    }
  }
  let code = parts.join('').replace(/-+/g, '-').replace(/^-|-$/g, '');
  if (!code) {
    let hash = 0;
    for (let i = 0; i < s.length; i++) {
      hash = (hash * 31 + s.charCodeAt(i)) >>> 0;
    }
    const hex = hash.toString(16).toUpperCase().padStart(12, '0').slice(0, 12);
    code = `V${hex}`;
  }
  return code.slice(0, 64);
}

export function skuSegmentKey(code: string, maxLen: number = SKU_SEGMENT_MAX): string {
  const cleaned = (code || '').trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
  return cleaned.slice(0, maxLen);
}

export function isAutoGeneratedValueCode(code: string): boolean {
  return AUTO_VALUE_CODE_RE.test((code || '').trim().toUpperCase());
}

/** True when inline create must ask for an explicit English code (Arabic-only, auto-hash, or segment clash). */
export function needsValueCodePrompt(label: string, existingCodes: string[] = []): boolean {
  const derived = normalizeAttributeCodeClient(label);
  if (!derived || isAutoGeneratedValueCode(derived)) {
    return true;
  }
  const seg = skuSegmentKey(derived);
  if (!seg) {
    return true;
  }
  for (const existing of existingCodes) {
    if (skuSegmentKey(existing) === seg) {
      return true;
    }
  }
  return false;
}

export function deriveValueCodeFromLabel(label: string): string {
  return normalizeAttributeCodeClient(label);
}
