"""phase2_epic_20_21_22_23_new_tables

Revision ID: 150169d2047f
Revises: 7e8d9f2a3b4c
Create Date: 2026-05-12 19:09:50.463374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150169d2047f'
down_revision: Union[str, None] = '7e8d9f2a3b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_day_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('cart_date', sa.Date(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_cart_day_sequences_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_day_sequences'))
    )
    op.create_index(op.f('ix_cart_day_sequences_branch_id'), 'cart_day_sequences', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cart_day_sequences_cart_date'), 'cart_day_sequences', ['cart_date'], unique=False)
    op.create_index(op.f('ix_cart_day_sequences_id'), 'cart_day_sequences', ['id'], unique=False)
    op.create_table('pos_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('expense_category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_pos_expenses_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_pos_expenses_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_pos_expenses_shift_id_pos_shifts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pos_expenses'))
    )
    op.create_index(op.f('ix_pos_expenses_branch_id'), 'pos_expenses', ['branch_id'], unique=False)
    op.create_index(op.f('ix_pos_expenses_id'), 'pos_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_pos_expenses_shift_id'), 'pos_expenses', ['shift_id'], unique=False)
    op.alter_column('branch_product_costs', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('goods_receipt_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Epic 20.1: multi-currency columns — existing rows need a backfill before NOT NULL
    op.add_column('journal_entry_lines', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.execute(sa.text("UPDATE journal_entry_lines SET currency_code = 'LYD' WHERE currency_code IS NULL"))
    op.alter_column(
        'journal_entry_lines',
        'currency_code',
        existing_type=sa.String(length=3),
        nullable=False,
    )
    op.add_column('journal_entry_lines', sa.Column('transaction_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('journal_entry_lines', sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True))
    op.alter_column('pos_cart_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('pos_carts', sa.Column('daily_cart_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pos_carts_daily_cart_number'), 'pos_carts', ['daily_cart_number'], unique=False)
    op.alter_column('purchase_order_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_invoice_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_return_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_levels', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_movements', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_movements', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_levels', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_return_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_invoice_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_order_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_pos_carts_daily_cart_number'), table_name='pos_carts')
    op.drop_column('pos_carts', 'daily_cart_number')
    op.alter_column('pos_cart_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('journal_entry_lines', 'fx_rate')
    op.drop_column('journal_entry_lines', 'transaction_amount')
    op.drop_column('journal_entry_lines', 'currency_code')
    op.alter_column('goods_receipt_lines', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('branch_product_costs', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_pos_expenses_shift_id'), table_name='pos_expenses')
    op.drop_index(op.f('ix_pos_expenses_id'), table_name='pos_expenses')
    op.drop_index(op.f('ix_pos_expenses_branch_id'), table_name='pos_expenses')
    op.drop_table('pos_expenses')
    op.drop_index(op.f('ix_cart_day_sequences_id'), table_name='cart_day_sequences')
    op.drop_index(op.f('ix_cart_day_sequences_cart_date'), table_name='cart_day_sequences')
    op.drop_index(op.f('ix_cart_day_sequences_branch_id'), table_name='cart_day_sequences')
    op.drop_table('cart_day_sequences')
    # ### end Alembic commands ###
