"""crm_loyalty_discount_Tables

Revision ID: 227b011283f2
Revises: e1d84cf80172
Create Date: 2026-04-11 23:48:36.077039

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "227b011283f2"
down_revision: str | None = "e1d84cf80172"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "discount_type",
            sa.Enum("FLAT", "PERCENTAGE", "BOGO", "COMBO", name="discounttype", native_enum=False),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("min_order_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("max_discount_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_product_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("buy_qty", sa.Integer(), nullable=True),
        sa.Column("get_qty", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "ACTIVE", "EXPIRED", "DISABLED", name="discountstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("stackable", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_discount_rules_code"), "discount_rules", ["code"], unique=True)
    op.create_index(
        op.f("ix_discount_rules_created_by_user_id"),
        "discount_rules",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_discount_rules_id"), "discount_rules", ["id"], unique=False)
    op.create_table(
        "loyalty_accrual_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("points_per_unit", sa.Integer(), nullable=False),
        sa.Column("currency_per_point", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loyalty_accrual_rules_created_by_user_id"),
        "loyalty_accrual_rules",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loyalty_accrual_rules_id"), "loyalty_accrual_rules", ["id"], unique=False
    )
    op.create_table(
        "loyalty_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum("CREDIT", "DEBIT", name="ledgerentrytype", native_enum=False),
            nullable=False,
        ),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column(
            "reason_code",
            sa.Enum(
                "PURCHASE",
                "MANUAL_ADJUSTMENT",
                "REDEMPTION",
                "EXPIRY",
                "CORRECTION",
                name="ledgerreasoncode",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reference_id", sa.String(length=128), nullable=True),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.Column("auditor_id", sa.Integer(), nullable=True),
        sa.Column("rule_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["auditor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customer_profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rule_id"], ["loyalty_accrual_rules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loyalty_ledger_auditor_id"), "loyalty_ledger", ["auditor_id"], unique=False
    )
    op.create_index(
        op.f("ix_loyalty_ledger_customer_id"), "loyalty_ledger", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_loyalty_ledger_id"), "loyalty_ledger", ["id"], unique=False)
    op.create_index(op.f("ix_loyalty_ledger_rule_id"), "loyalty_ledger", ["rule_id"], unique=False)
    op.create_table(
        "discount_usage_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discount_rule_id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("applied_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["applied_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["cart_id"], ["pos_carts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customer_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["discount_rule_id"], ["discount_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discount_usage_logs_applied_by_user_id"),
        "discount_usage_logs",
        ["applied_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discount_usage_logs_cart_id"), "discount_usage_logs", ["cart_id"], unique=False
    )
    op.create_index(
        op.f("ix_discount_usage_logs_customer_id"),
        "discount_usage_logs",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discount_usage_logs_discount_rule_id"),
        "discount_usage_logs",
        ["discount_rule_id"],
        unique=False,
    )
    op.create_index(op.f("ix_discount_usage_logs_id"), "discount_usage_logs", ["id"], unique=False)
    op.add_column("stock_levels", sa.Column("expiry_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_levels", "expiry_date")
    op.drop_index(op.f("ix_discount_usage_logs_id"), table_name="discount_usage_logs")
    op.drop_index(op.f("ix_discount_usage_logs_discount_rule_id"), table_name="discount_usage_logs")
    op.drop_index(op.f("ix_discount_usage_logs_customer_id"), table_name="discount_usage_logs")
    op.drop_index(op.f("ix_discount_usage_logs_cart_id"), table_name="discount_usage_logs")
    op.drop_index(
        op.f("ix_discount_usage_logs_applied_by_user_id"), table_name="discount_usage_logs"
    )
    op.drop_table("discount_usage_logs")
    op.drop_index(op.f("ix_loyalty_ledger_rule_id"), table_name="loyalty_ledger")
    op.drop_index(op.f("ix_loyalty_ledger_id"), table_name="loyalty_ledger")
    op.drop_index(op.f("ix_loyalty_ledger_customer_id"), table_name="loyalty_ledger")
    op.drop_index(op.f("ix_loyalty_ledger_auditor_id"), table_name="loyalty_ledger")
    op.drop_table("loyalty_ledger")
    op.drop_index(op.f("ix_loyalty_accrual_rules_id"), table_name="loyalty_accrual_rules")
    op.drop_index(
        op.f("ix_loyalty_accrual_rules_created_by_user_id"), table_name="loyalty_accrual_rules"
    )
    op.drop_table("loyalty_accrual_rules")
    op.drop_index(op.f("ix_discount_rules_id"), table_name="discount_rules")
    op.drop_index(op.f("ix_discount_rules_created_by_user_id"), table_name="discount_rules")
    op.drop_index(op.f("ix_discount_rules_code"), table_name="discount_rules")
    op.drop_table("discount_rules")
    # ### end Alembic commands ###
