"""Initial migration

Revision ID: 2305d9dddc2c
Revises: 01e42e4b52e7
Create Date: 2026-03-08 03:13:27.999980

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2305d9dddc2c"
down_revision: str | None = "01e42e4b52e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
