"""add_product_variants

Revision ID: 236903fab4eb
Revises: d4f8a1c2b3e4
Create Date: 2026-05-12 18:29:32.701545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '236903fab4eb'
down_revision: Union[str, None] = 'd4f8a1c2b3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('barcode', sa.String(length=128), nullable=True),
    sa.Column('attribute_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('barcode', deferrable='INITIALLY DEFERRED', name='uq_product_variants_barcode'),
    sa.UniqueConstraint('sku', name='uq_product_variants_sku')
    )
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.add_column('branch_product_costs', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_branch_product_costs_branch_product'), 'branch_product_costs', type_='unique')
    op.create_index(op.f('ix_branch_product_costs_variant_id'), 'branch_product_costs', ['variant_id'], unique=False)
    op.create_unique_constraint('uq_branch_product_costs_branch_product_variant', 'branch_product_costs', ['branch_id', 'product_id', 'variant_id'])
    op.create_foreign_key(op.f('fk_branch_product_costs_variant_id_product_variants'), 'branch_product_costs', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.add_column('category_attribute_defs', sa.Column('inherited_from_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_attribute_defs_inherited_from_category_id'), 'category_attribute_defs', ['inherited_from_category_id'], unique=False)
    op.create_foreign_key(op.f('fk_category_attribute_defs_inherited_from_category_id_categories'), 'category_attribute_defs', 'categories', ['inherited_from_category_id'], ['id'], ondelete='SET NULL')
    op.add_column('goods_receipt_lines', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_goods_receipt_lines_variant_id'), 'goods_receipt_lines', ['variant_id'], unique=False)
    op.create_foreign_key(op.f('fk_goods_receipt_lines_variant_id_product_variants'), 'goods_receipt_lines', 'product_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('pos_cart_lines', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pos_cart_lines_variant_id'), 'pos_cart_lines', ['variant_id'], unique=False)
    op.create_foreign_key(op.f('fk_pos_cart_lines_variant_id_product_variants'), 'pos_cart_lines', 'product_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_product_categories_category_id'), table_name='product_categories')
    op.add_column('purchase_order_lines', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_order_lines_variant_id'), 'purchase_order_lines', ['variant_id'], unique=False)
    op.create_foreign_key(op.f('fk_purchase_order_lines_variant_id_product_variants'), 'purchase_order_lines', 'product_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('sales_invoice_lines', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_invoice_lines_variant_id'), 'sales_invoice_lines', ['variant_id'], unique=False)
    op.create_foreign_key(op.f('fk_sales_invoice_lines_variant_id_product_variants'), 'sales_invoice_lines', 'product_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('sales_return_lines', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_return_lines_variant_id'), 'sales_return_lines', ['variant_id'], unique=False)
    op.create_foreign_key(op.f('fk_sales_return_lines_variant_id_product_variants'), 'sales_return_lines', 'product_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('stock_levels', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_stock_levels_branch_product'), 'stock_levels', type_='unique')
    op.create_index(op.f('ix_stock_levels_variant_id'), 'stock_levels', ['variant_id'], unique=False)
    op.create_unique_constraint('uq_stock_levels_branch_product_variant', 'stock_levels', ['branch_id', 'product_id', 'variant_id'])
    op.create_foreign_key(op.f('fk_stock_levels_variant_id_product_variants'), 'stock_levels', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_movements', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_variant_id'), 'stock_movements', ['variant_id'], unique=False)
    op.create_foreign_key(op.f('fk_stock_movements_variant_id_product_variants'), 'stock_movements', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.add_column('transfer_lines', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transfer_lines_variant_id'), 'transfer_lines', ['variant_id'], unique=False)
    op.create_foreign_key(op.f('fk_transfer_lines_variant_id_product_variants'), 'transfer_lines', 'product_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transfer_lines_variant_id_product_variants'), 'transfer_lines', type_='foreignkey')
    op.drop_index(op.f('ix_transfer_lines_variant_id'), table_name='transfer_lines')
    op.drop_column('transfer_lines', 'variant_id')
    op.drop_constraint(op.f('fk_stock_movements_variant_id_product_variants'), 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_variant_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'variant_id')
    op.drop_constraint(op.f('fk_stock_levels_variant_id_product_variants'), 'stock_levels', type_='foreignkey')
    op.drop_constraint('uq_stock_levels_branch_product_variant', 'stock_levels', type_='unique')
    op.drop_index(op.f('ix_stock_levels_variant_id'), table_name='stock_levels')
    op.create_unique_constraint(op.f('uq_stock_levels_branch_product'), 'stock_levels', ['branch_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('stock_levels', 'variant_id')
    op.drop_constraint(op.f('fk_sales_return_lines_variant_id_product_variants'), 'sales_return_lines', type_='foreignkey')
    op.drop_index(op.f('ix_sales_return_lines_variant_id'), table_name='sales_return_lines')
    op.drop_column('sales_return_lines', 'variant_id')
    op.drop_constraint(op.f('fk_sales_invoice_lines_variant_id_product_variants'), 'sales_invoice_lines', type_='foreignkey')
    op.drop_index(op.f('ix_sales_invoice_lines_variant_id'), table_name='sales_invoice_lines')
    op.drop_column('sales_invoice_lines', 'variant_id')
    op.drop_constraint(op.f('fk_purchase_order_lines_variant_id_product_variants'), 'purchase_order_lines', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_order_lines_variant_id'), table_name='purchase_order_lines')
    op.drop_column('purchase_order_lines', 'variant_id')
    op.create_index(op.f('ix_product_categories_category_id'), 'product_categories', ['category_id'], unique=False)
    op.drop_constraint(op.f('fk_pos_cart_lines_variant_id_product_variants'), 'pos_cart_lines', type_='foreignkey')
    op.drop_index(op.f('ix_pos_cart_lines_variant_id'), table_name='pos_cart_lines')
    op.drop_column('pos_cart_lines', 'variant_id')
    op.drop_constraint(op.f('fk_goods_receipt_lines_variant_id_product_variants'), 'goods_receipt_lines', type_='foreignkey')
    op.drop_index(op.f('ix_goods_receipt_lines_variant_id'), table_name='goods_receipt_lines')
    op.drop_column('goods_receipt_lines', 'variant_id')
    op.drop_constraint(op.f('fk_category_attribute_defs_inherited_from_category_id_categories'), 'category_attribute_defs', type_='foreignkey')
    op.drop_index(op.f('ix_category_attribute_defs_inherited_from_category_id'), table_name='category_attribute_defs')
    op.drop_column('category_attribute_defs', 'inherited_from_category_id')
    op.drop_constraint(op.f('fk_branch_product_costs_variant_id_product_variants'), 'branch_product_costs', type_='foreignkey')
    op.drop_constraint('uq_branch_product_costs_branch_product_variant', 'branch_product_costs', type_='unique')
    op.drop_index(op.f('ix_branch_product_costs_variant_id'), table_name='branch_product_costs')
    op.create_unique_constraint(op.f('uq_branch_product_costs_branch_product'), 'branch_product_costs', ['branch_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('branch_product_costs', 'variant_id')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
