"""epic1_identity_access_auditing

Revision ID: 288f4b15c635
Revises: 2305d9dddc2c
Create Date: 2026-03-15 20:51:37.113323

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "288f4b15c635"
down_revision: str | None = "2305d9dddc2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
