"""add Ai suggstion tools

Revision ID: 305898f5e49b
Revises: a1b2c3d4e5f6
Create Date: 2026-04-21 18:22:54.048981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305898f5e49b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_id'), 'notification_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_schedule_id'), 'notification_deliveries', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_notification_runs_id'), 'notification_runs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_schedules_id'), 'notification_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_schedules_id'), table_name='notification_schedules')
    op.drop_index(op.f('ix_notification_runs_id'), table_name='notification_runs')
    op.drop_index(op.f('ix_notification_deliveries_schedule_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    # ### end Alembic commands ###
