"""change all Float to Decimal

Revision ID: 3a63a307cc76
Revises: 6f3d5a9b0c11
Create Date: 2026-04-18 18:55:43.697412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a63a307cc76'
down_revision: Union[str, None] = '6f3d5a9b0c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('journal_entries_idempotency_key_key'), 'journal_entries', type_='unique')
    op.create_unique_constraint('uq_journal_entries_idempotency', 'journal_entries', ['idempotency_key'])
    op.drop_constraint(op.f('user_onboardings_user_id_key'), 'user_onboardings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_onboardings_user_id_key'), 'user_onboardings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_journal_entries_idempotency', 'journal_entries', type_='unique')
    op.create_unique_constraint(op.f('journal_entries_idempotency_key_key'), 'journal_entries', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
