"""add stock count tables

Revision ID: 76cc97cdeddc
Revises: u1v2w3x4y5z6
Create Date: 2026-06-01 09:28:42.176709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cc97cdeddc'
down_revision: Union[str, None] = 'u1v2w3x4y5z6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attribute_values_id'), 'attribute_values', ['id'], unique=False)
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.alter_column('chart_accounts', 'subledger_kind',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('none', 'customer', 'supplier', 'employee', name='subledgerkind', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_payment_terms_code'), 'payment_terms', type_='unique')
    op.create_index(op.f('ix_payment_terms_id'), 'payment_terms', ['id'], unique=False)
    op.create_index(op.f('ix_product_attribute_line_values_id'), 'product_attribute_line_values', ['id'], unique=False)
    op.create_index(op.f('ix_product_attribute_lines_id'), 'product_attribute_lines', ['id'], unique=False)
    op.drop_index(op.f('ix_product_tax_definitions_product_id'), table_name='product_tax_definitions')
    op.create_index(op.f('ix_product_unit_conversions_id'), 'product_unit_conversions', ['id'], unique=False)
    op.drop_index(op.f('ix_pva_attribute_value_filter'), table_name='product_variant_attributes')
    op.create_index(op.f('ix_product_variant_attributes_attribute_id'), 'product_variant_attributes', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_variant_attributes_attribute_value_id'), 'product_variant_attributes', ['attribute_value_id'], unique=False)
    op.create_index(op.f('ix_product_variant_attributes_id'), 'product_variant_attributes', ['id'], unique=False)
    op.create_unique_constraint('uq_product_variants_reference_code', 'product_variants', ['reference_code'])
    op.create_index(op.f('ix_stock_count_lines_id'), 'stock_count_lines', ['id'], unique=False)
    op.create_index(op.f('ix_stock_count_sessions_created_by'), 'stock_count_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_stock_count_sessions_id'), 'stock_count_sessions', ['id'], unique=False)
    op.drop_constraint(op.f('uq_tax_definitions_code'), 'tax_definitions', type_='unique')
    op.drop_index(op.f('ix_tax_definitions_code'), table_name='tax_definitions')
    op.create_index(op.f('ix_tax_definitions_code'), 'tax_definitions', ['code'], unique=True)
    op.drop_constraint(op.f('uq_units_of_measure_code'), 'units_of_measure', type_='unique')
    op.create_index(op.f('ix_units_of_measure_id'), 'units_of_measure', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_of_measure_id'), table_name='units_of_measure')
    op.create_unique_constraint(op.f('uq_units_of_measure_code'), 'units_of_measure', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tax_definitions_code'), table_name='tax_definitions')
    op.create_index(op.f('ix_tax_definitions_code'), 'tax_definitions', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_tax_definitions_code'), 'tax_definitions', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_stock_count_sessions_id'), table_name='stock_count_sessions')
    op.drop_index(op.f('ix_stock_count_sessions_created_by'), table_name='stock_count_sessions')
    op.drop_index(op.f('ix_stock_count_lines_id'), table_name='stock_count_lines')
    op.drop_constraint('uq_product_variants_reference_code', 'product_variants', type_='unique')
    op.drop_index(op.f('ix_product_variant_attributes_id'), table_name='product_variant_attributes')
    op.drop_index(op.f('ix_product_variant_attributes_attribute_value_id'), table_name='product_variant_attributes')
    op.drop_index(op.f('ix_product_variant_attributes_attribute_id'), table_name='product_variant_attributes')
    op.create_index(op.f('ix_pva_attribute_value_filter'), 'product_variant_attributes', ['attribute_id', 'attribute_value_id'], unique=False)
    op.drop_index(op.f('ix_product_unit_conversions_id'), table_name='product_unit_conversions')
    op.create_index(op.f('ix_product_tax_definitions_product_id'), 'product_tax_definitions', ['product_id'], unique=False)
    op.drop_index(op.f('ix_product_attribute_lines_id'), table_name='product_attribute_lines')
    op.drop_index(op.f('ix_product_attribute_line_values_id'), table_name='product_attribute_line_values')
    op.drop_index(op.f('ix_payment_terms_id'), table_name='payment_terms')
    op.create_unique_constraint(op.f('uq_payment_terms_code'), 'payment_terms', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('chart_accounts', 'subledger_kind',
               existing_type=sa.Enum('none', 'customer', 'supplier', 'employee', name='subledgerkind', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_index(op.f('ix_attribute_values_id'), table_name='attribute_values')
    # ### end Alembic commands ###
