"""make_variant_id_not_null

Revision ID: 7e8d9f2a3b4c
Revises: 236903fab4eb
Create Date: 2026-05-12 18:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e8d9f2a3b4c'
down_revision: Union[str, None] = '236903fab4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Make variant_id NOT NULL in all line tables.
    
    Prerequisites:
    - product_variants table must exist
    - All products must have a variant created (backfill complete)
    - All existing rows in line tables must have variant_id filled
    """
    # ### commands auto generated by Alembic - adjusted for Epic 18.5 ###
    
    # 1. stock_movements
    op.alter_column('stock_movements', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 2. stock_levels
    op.alter_column('stock_levels', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 3. branch_product_costs
    op.alter_column('branch_product_costs', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 4. pos_cart_lines
    op.alter_column('pos_cart_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 5. sales_invoice_lines
    op.alter_column('sales_invoice_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 6. purchase_order_lines
    op.alter_column('purchase_order_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 7. goods_receipt_lines
    op.alter_column('goods_receipt_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 8. transfer_lines
    op.alter_column('transfer_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # 9. sales_return_lines
    op.alter_column('sales_return_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=False,
                    existing_server_default=None)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert variant_id to nullable."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverse order (9 to 1)
    op.alter_column('sales_return_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('transfer_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('goods_receipt_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('purchase_order_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('sales_invoice_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('pos_cart_lines', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('branch_product_costs', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('stock_levels', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    op.alter_column('stock_movements', 'variant_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    
    # ### end Alembic commands ###
