"""Add city column to users

Revision ID: 88cfd8467f27
Revises: e8f9a0b1c2d3
Create Date: 2026-05-01 22:10:24.932753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cfd8467f27'
down_revision: Union[str, None] = 'e8f9a0b1c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_logs_clock_in_at'), table_name='attendance_logs')
    op.drop_index(op.f('ix_goods_receipts_idempotency_key'), table_name='goods_receipts', postgresql_where='(idempotency_key IS NOT NULL)')
    op.create_unique_constraint(None, 'goods_receipts', ['idempotency_key'])
    op.drop_index(op.f('ix_invoice_scans_catalog_match_apply_idempotency_key'), table_name='invoice_scans', postgresql_where='(catalog_match_apply_idempotency_key IS NOT NULL)')
    op.create_unique_constraint(None, 'invoice_scans', ['catalog_match_apply_idempotency_key'])
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.drop_constraint(None, 'invoice_scans', type_='unique')
    op.create_index(op.f('ix_invoice_scans_catalog_match_apply_idempotency_key'), 'invoice_scans', ['catalog_match_apply_idempotency_key'], unique=True, postgresql_where='(catalog_match_apply_idempotency_key IS NOT NULL)')
    op.drop_constraint(None, 'goods_receipts', type_='unique')
    op.create_index(op.f('ix_goods_receipts_idempotency_key'), 'goods_receipts', ['idempotency_key'], unique=True, postgresql_where='(idempotency_key IS NOT NULL)')
    op.create_index(op.f('ix_attendance_logs_clock_in_at'), 'attendance_logs', ['clock_in_at'], unique=False)
    # ### end Alembic commands ###
