"""crm_loyalty_discount_analytics

Revision ID: 8c6e82fe0802
Revises: 227b011283f2
Create Date: 2026-04-12 00:18:15.179006

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8c6e82fe0802"
down_revision: str | None = "227b011283f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
