"""fix Date Problem

Revision ID: bb3d116e80a1
Revises: 5b8f2c1d9e4a
Create Date: 2026-04-19 10:38:46.236720

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bb3d116e80a1"
down_revision: str | None = "5b8f2c1d9e4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
