"""fix Date Problem

Revision ID: bb3d116e80a1
Revises: 5b8f2c1d9e4a
Create Date: 2026-04-19 10:38:46.236720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3d116e80a1'
down_revision: Union[str, None] = '5b8f2c1d9e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
