"""test epic 3

Revision ID: bffd7913ac74
Revises: c3d4e5f6a7b8
Create Date: 2026-03-26 20:44:30.573120

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bffd7913ac74"
down_revision: str | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
