"""add index ix_pos_cart_lines_uom_id

Revision ID: c15cec5e5b2a
Revises: y0z1a2b3c4d5
Create Date: 2026-06-04 00:53:17.605024

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c15cec5e5b2a"
down_revision: str | None = "y0z1a2b3c4d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_pos_cart_lines_uom_id"), "pos_cart_lines", ["uom_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pos_cart_lines_uom_id"), table_name="pos_cart_lines")
    # ### end Alembic commands ###
