"""Add production orders, BoM, cost layers, AI usage log tables

Revision ID: c2ad13cd9886
Revises: 150169d2047f
Create Date: 2026-05-12 19:30:59.448553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ad13cd9886'
down_revision: Union[str, None] = '150169d2047f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
