"""add_hr_payroll_tables

Revision ID: e1d84cf80172
Revises: f926accd7928
Create Date: 2026-04-06 10:02:29.143685

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1d84cf80172"
down_revision: str | None = "f926accd7928"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("base_salary", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("hourly_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("bank_account", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_profiles_id"), "employee_profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_employee_profiles_user_id"), "employee_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "attendance_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_profile_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("clock_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("clock_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["employee_profile_id"], ["employee_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_logs_branch_id"), "attendance_logs", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_logs_employee_profile_id"),
        "attendance_logs",
        ["employee_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_attendance_logs_id"), "attendance_logs", ["id"], unique=False)
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "leave_type",
            sa.Enum("VACATION", "SICK", "PERSONAL", name="leavetype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="leavestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=1024), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_profile_id"], ["employee_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_requests_employee_profile_id"),
        "leave_requests",
        ["employee_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_leave_requests_id"), "leave_requests", ["id"], unique=False)
    op.create_table(
        "payslips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_profile_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("hours_worked", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deductions", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "APPROVED", name="payslipstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("immutable_hash", sa.String(length=64), nullable=False),
        sa.Column("approved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["employee_profile_id"], ["employee_profiles.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("immutable_hash"),
    )
    op.create_index(
        op.f("ix_payslips_employee_profile_id"), "payslips", ["employee_profile_id"], unique=False
    )
    op.create_index(op.f("ix_payslips_id"), "payslips", ["id"], unique=False)
    op.create_table(
        "weekly_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_profile_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_day_off", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["employee_profile_id"], ["employee_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weekly_schedules_branch_id"), "weekly_schedules", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_weekly_schedules_employee_profile_id"),
        "weekly_schedules",
        ["employee_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_weekly_schedules_id"), "weekly_schedules", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_schedules_id"), table_name="weekly_schedules")
    op.drop_index(op.f("ix_weekly_schedules_employee_profile_id"), table_name="weekly_schedules")
    op.drop_index(op.f("ix_weekly_schedules_branch_id"), table_name="weekly_schedules")
    op.drop_table("weekly_schedules")
    op.drop_index(op.f("ix_payslips_id"), table_name="payslips")
    op.drop_index(op.f("ix_payslips_employee_profile_id"), table_name="payslips")
    op.drop_table("payslips")
    op.drop_index(op.f("ix_leave_requests_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_employee_profile_id"), table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(op.f("ix_attendance_logs_id"), table_name="attendance_logs")
    op.drop_index(op.f("ix_attendance_logs_employee_profile_id"), table_name="attendance_logs")
    op.drop_index(op.f("ix_attendance_logs_branch_id"), table_name="attendance_logs")
    op.drop_table("attendance_logs")
    op.drop_index(op.f("ix_employee_profiles_user_id"), table_name="employee_profiles")
    op.drop_index(op.f("ix_employee_profiles_id"), table_name="employee_profiles")
    op.drop_table("employee_profiles")
    # ### end Alembic commands ###
