"""add_bom_fifo_ai_models

Revision ID: f441af8774f2
Revises: c2ad13cd9886
Create Date: 2026-05-12 19:37:04.758213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f441af8774f2'
down_revision: Union[str, None] = 'c2ad13cd9886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
