"""init_database

Revision ID: f926accd7928
Revises:
Create Date: 2026-03-29 12:39:14.352700

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f926accd7928"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_branches_code"), "branches", ["code"], unique=True)
    op.create_index(op.f("ix_branches_id"), "branches", ["id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "name", name="uq_categories_parent_name"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=False)
    op.create_table(
        "examples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_examples_id"), "examples", ["id"], unique=False)
    op.create_table(
        "invoice_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("raw_input_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parsed_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("override_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_scans_id"), "invoice_scans", ["id"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource", "action", name="uq_permission_resource_action"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "category_attribute_defs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "key", name="uq_cat_attr_defs_category_key"),
    )
    op.create_index(
        op.f("ix_category_attribute_defs_category_id"),
        "category_attribute_defs",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_category_attribute_defs_id"), "category_attribute_defs", ["id"], unique=False
    )
    op.create_table(
        "pos_terminals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("terminal_code", sa.String(length=128), nullable=False),
        sa.Column("api_key_hash", sa.String(length=255), nullable=False),
        sa.Column("is_authorized", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pos_terminals_id"), "pos_terminals", ["id"], unique=False)
    op.create_index(
        op.f("ix_pos_terminals_terminal_code"), "pos_terminals", ["terminal_code"], unique=True
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("barcode", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_barcode"), "products", ["barcode"], unique=True)
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_permissions_id"), "role_permissions", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("preferred_language", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_table(
        "customer_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_temporary", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_profiles_id"), "customer_profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_customer_profiles_phone"), "customer_profiles", ["phone"], unique=False
    )
    op.create_table(
        "global_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_global_config_id"), "global_config", ["id"], unique=False)
    op.create_index(op.f("ix_global_config_key"), "global_config", ["key"], unique=True)
    op.create_table(
        "goods_receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("supplier_name", sa.String(length=255), nullable=True),
        sa.Column("invoice_number", sa.String(length=128), nullable=True),
        sa.Column("source_invoice_scan_id", sa.Integer(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_invoice_scan_id"], ["invoice_scans.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goods_receipts_branch_id"), "goods_receipts", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipts_created_by_user_id"),
        "goods_receipts",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_goods_receipts_id"), "goods_receipts", ["id"], unique=False)
    op.create_index(
        op.f("ix_goods_receipts_invoice_number"), "goods_receipts", ["invoice_number"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipts_source_invoice_scan_id"),
        "goods_receipts",
        ["source_invoice_scan_id"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_id"), "password_reset_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_table(
        "pos_shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("terminal_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("opened_by_user_id", sa.Integer(), nullable=True),
        sa.Column("closed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("opening_float", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expected_cash", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("declared_cash", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("variance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["closed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["opened_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["terminal_id"], ["pos_terminals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pos_shifts_branch_id"), "pos_shifts", ["branch_id"], unique=False)
    op.create_index(
        op.f("ix_pos_shifts_closed_by_user_id"), "pos_shifts", ["closed_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_pos_shifts_id"), "pos_shifts", ["id"], unique=False)
    op.create_index(
        op.f("ix_pos_shifts_opened_by_user_id"), "pos_shifts", ["opened_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_pos_shifts_terminal_id"), "pos_shifts", ["terminal_id"], unique=False)
    op.create_index(
        "uq_pos_shifts_terminal_open",
        "pos_shifts",
        ["terminal_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.String(length=1024), nullable=True),
        sa.Column("expected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_orders_created_by_user_id"),
        "purchase_orders",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_purchase_orders_id"), "purchase_orders", ["id"], unique=False)
    op.create_index(
        op.f("ix_purchase_orders_supplier_name"), "purchase_orders", ["supplier_name"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False)
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=False
    )
    op.create_table(
        "stock_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "product_id", name="uq_stock_levels_branch_product"),
    )
    op.create_index(op.f("ix_stock_levels_branch_id"), "stock_levels", ["branch_id"], unique=False)
    op.create_index(op.f("ix_stock_levels_id"), "stock_levels", ["id"], unique=False)
    op.create_index(
        op.f("ix_stock_levels_product_id"), "stock_levels", ["product_id"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty_delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("ref_type", sa.String(length=64), nullable=True),
        sa.Column("ref_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_stock_movements_idempotency_key"),
    )
    op.create_index(
        op.f("ix_stock_movements_branch_id"), "stock_movements", ["branch_id"], unique=False
    )
    op.create_index(op.f("ix_stock_movements_id"), "stock_movements", ["id"], unique=False)
    op.create_index(
        op.f("ix_stock_movements_product_id"), "stock_movements", ["product_id"], unique=False
    )
    op.create_table(
        "transfer_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_branch_id", sa.Integer(), nullable=False),
        sa.Column("to_branch_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["from_branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transfer_batches_created_by_user_id"),
        "transfer_batches",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transfer_batches_from_branch_id"),
        "transfer_batches",
        ["from_branch_id"],
        unique=False,
    )
    op.create_index(op.f("ix_transfer_batches_id"), "transfer_batches", ["id"], unique=False)
    op.create_index(
        op.f("ix_transfer_batches_to_branch_id"), "transfer_batches", ["to_branch_id"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", "branch_id", name="uq_user_role_branch"),
    )
    op.create_index(op.f("ix_user_roles_id"), "user_roles", ["id"], unique=False)
    op.create_table(
        "customer_onboarding_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customer_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_onboarding_tokens_customer_id"),
        "customer_onboarding_tokens",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_onboarding_tokens_id"), "customer_onboarding_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_onboarding_tokens_token_hash"),
        "customer_onboarding_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "goods_receipt_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("goods_receipt_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["goods_receipt_id"], ["goods_receipts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_goods_receipt_id"),
        "goods_receipt_lines",
        ["goods_receipt_id"],
        unique=False,
    )
    op.create_index(op.f("ix_goods_receipt_lines_id"), "goods_receipt_lines", ["id"], unique=False)
    op.create_index(
        op.f("ix_goods_receipt_lines_product_id"),
        "goods_receipt_lines",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "pos_carts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("terminal_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["customer_id"], ["customer_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["shift_id"], ["pos_shifts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["terminal_id"], ["pos_terminals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pos_carts_branch_id"), "pos_carts", ["branch_id"], unique=False)
    op.create_index(op.f("ix_pos_carts_customer_id"), "pos_carts", ["customer_id"], unique=False)
    op.create_index(op.f("ix_pos_carts_id"), "pos_carts", ["id"], unique=False)
    op.create_index(op.f("ix_pos_carts_shift_id"), "pos_carts", ["shift_id"], unique=False)
    op.create_index(op.f("ix_pos_carts_terminal_id"), "pos_carts", ["terminal_id"], unique=False)
    op.create_table(
        "pos_cash_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["shift_id"], ["pos_shifts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pos_cash_events_id"), "pos_cash_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_pos_cash_events_shift_id"), "pos_cash_events", ["shift_id"], unique=False
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["purchase_order_id"], ["purchase_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_id"), "purchase_order_lines", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_lines_product_id"),
        "purchase_order_lines",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_lines_purchase_order_id"),
        "purchase_order_lines",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "transfer_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transfer_batch_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["transfer_batch_id"], ["transfer_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transfer_lines_id"), "transfer_lines", ["id"], unique=False)
    op.create_index(
        op.f("ix_transfer_lines_product_id"), "transfer_lines", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfer_lines_transfer_batch_id"),
        "transfer_lines",
        ["transfer_batch_id"],
        unique=False,
    )
    op.create_table(
        "z_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("report_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["shift_id"], ["pos_shifts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_z_reports_id"), "z_reports", ["id"], unique=False)
    op.create_index(op.f("ix_z_reports_shift_id"), "z_reports", ["shift_id"], unique=True)
    op.create_table(
        "payment_intents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["pos_carts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cart_id", "status", name="uq_payment_intents_cart_status"),
    )
    op.create_index(
        op.f("ix_payment_intents_cart_id"), "payment_intents", ["cart_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_intents_external_id"), "payment_intents", ["external_id"], unique=False
    )
    op.create_index(op.f("ix_payment_intents_id"), "payment_intents", ["id"], unique=False)
    op.create_table(
        "pos_cart_discounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["pos_carts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pos_cart_discounts_cart_id"), "pos_cart_discounts", ["cart_id"], unique=False
    )
    op.create_index(op.f("ix_pos_cart_discounts_id"), "pos_cart_discounts", ["id"], unique=False)
    op.create_table(
        "pos_cart_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["pos_carts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pos_cart_events_cart_id"), "pos_cart_events", ["cart_id"], unique=False
    )
    op.create_index(op.f("ix_pos_cart_events_id"), "pos_cart_events", ["id"], unique=False)
    op.create_table(
        "pos_cart_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["pos_carts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pos_cart_lines_cart_id"), "pos_cart_lines", ["cart_id"], unique=False)
    op.create_index(op.f("ix_pos_cart_lines_id"), "pos_cart_lines", ["id"], unique=False)
    op.create_index(
        op.f("ix_pos_cart_lines_product_id"), "pos_cart_lines", ["product_id"], unique=False
    )
    op.create_table(
        "sales_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(length=64), nullable=False),
        sa.Column("invoice_barcode", sa.String(length=128), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("terminal_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["cart_id"], ["pos_carts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customer_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["terminal_id"], ["pos_terminals.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_invoices_branch_id"), "sales_invoices", ["branch_id"], unique=False
    )
    op.create_index(op.f("ix_sales_invoices_cart_id"), "sales_invoices", ["cart_id"], unique=True)
    op.create_index(op.f("ix_sales_invoices_id"), "sales_invoices", ["id"], unique=False)
    op.create_index(
        op.f("ix_sales_invoices_invoice_barcode"),
        "sales_invoices",
        ["invoice_barcode"],
        unique=True,
    )
    op.create_index(
        op.f("ix_sales_invoices_invoice_number"), "sales_invoices", ["invoice_number"], unique=True
    )
    op.create_index(
        op.f("ix_sales_invoices_terminal_id"), "sales_invoices", ["terminal_id"], unique=False
    )
    op.create_table(
        "invoice_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sales_invoice_id", sa.Integer(), nullable=False),
        sa.Column("payment_intent_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["payment_intent_id"], ["payment_intents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sales_invoice_id"], ["sales_invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_payments_id"), "invoice_payments", ["id"], unique=False)
    op.create_index(
        op.f("ix_invoice_payments_payment_intent_id"),
        "invoice_payments",
        ["payment_intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_payments_sales_invoice_id"),
        "invoice_payments",
        ["sales_invoice_id"],
        unique=False,
    )
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_intent_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["payment_intent_id"], ["payment_intents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_attempts_id"), "payment_attempts", ["id"], unique=False)
    op.create_index(
        op.f("ix_payment_attempts_idempotency_key"),
        "payment_attempts",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payment_attempts_payment_intent_id"),
        "payment_attempts",
        ["payment_intent_id"],
        unique=False,
    )
    op.create_table(
        "payment_receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_intent_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.Column("redacted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["payment_intent_id"], ["payment_intents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_receipts_id"), "payment_receipts", ["id"], unique=False)
    op.create_index(
        op.f("ix_payment_receipts_payment_intent_id"),
        "payment_receipts",
        ["payment_intent_id"],
        unique=False,
    )
    op.create_table(
        "sales_invoice_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sales_invoice_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sales_invoice_id"], ["sales_invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_invoice_lines_id"), "sales_invoice_lines", ["id"], unique=False)
    op.create_index(
        op.f("ix_sales_invoice_lines_product_id"),
        "sales_invoice_lines",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_invoice_lines_sales_invoice_id"),
        "sales_invoice_lines",
        ["sales_invoice_id"],
        unique=False,
    )
    op.create_table(
        "sales_returns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sales_invoice_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sales_invoice_id"], ["sales_invoices.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_returns_id"), "sales_returns", ["id"], unique=False)
    op.create_index(
        op.f("ix_sales_returns_sales_invoice_id"),
        "sales_returns",
        ["sales_invoice_id"],
        unique=False,
    )
    op.create_table(
        "credit_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sales_return_id", sa.Integer(), nullable=False),
        sa.Column("credit_number", sa.String(length=64), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["sales_return_id"], ["sales_returns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_notes_credit_number"), "credit_notes", ["credit_number"], unique=True
    )
    op.create_index(op.f("ix_credit_notes_id"), "credit_notes", ["id"], unique=False)
    op.create_index(
        op.f("ix_credit_notes_sales_return_id"), "credit_notes", ["sales_return_id"], unique=True
    )
    op.create_table(
        "exchange_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sales_return_id", sa.Integer(), nullable=False),
        sa.Column("new_cart_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["new_cart_id"], ["pos_carts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sales_return_id"], ["sales_returns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exchange_links_id"), "exchange_links", ["id"], unique=False)
    op.create_index(
        op.f("ix_exchange_links_new_cart_id"), "exchange_links", ["new_cart_id"], unique=False
    )
    op.create_index(
        op.f("ix_exchange_links_sales_return_id"),
        "exchange_links",
        ["sales_return_id"],
        unique=False,
    )
    op.create_table(
        "sales_return_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sales_return_id", sa.Integer(), nullable=False),
        sa.Column("sales_invoice_line_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["sales_invoice_line_id"], ["sales_invoice_lines.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["sales_return_id"], ["sales_returns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_return_lines_id"), "sales_return_lines", ["id"], unique=False)
    op.create_index(
        op.f("ix_sales_return_lines_product_id"), "sales_return_lines", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_return_lines_sales_invoice_line_id"),
        "sales_return_lines",
        ["sales_invoice_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_return_lines_sales_return_id"),
        "sales_return_lines",
        ["sales_return_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_return_lines_sales_return_id"), table_name="sales_return_lines")
    op.drop_index(
        op.f("ix_sales_return_lines_sales_invoice_line_id"), table_name="sales_return_lines"
    )
    op.drop_index(op.f("ix_sales_return_lines_product_id"), table_name="sales_return_lines")
    op.drop_index(op.f("ix_sales_return_lines_id"), table_name="sales_return_lines")
    op.drop_table("sales_return_lines")
    op.drop_index(op.f("ix_exchange_links_sales_return_id"), table_name="exchange_links")
    op.drop_index(op.f("ix_exchange_links_new_cart_id"), table_name="exchange_links")
    op.drop_index(op.f("ix_exchange_links_id"), table_name="exchange_links")
    op.drop_table("exchange_links")
    op.drop_index(op.f("ix_credit_notes_sales_return_id"), table_name="credit_notes")
    op.drop_index(op.f("ix_credit_notes_id"), table_name="credit_notes")
    op.drop_index(op.f("ix_credit_notes_credit_number"), table_name="credit_notes")
    op.drop_table("credit_notes")
    op.drop_index(op.f("ix_sales_returns_sales_invoice_id"), table_name="sales_returns")
    op.drop_index(op.f("ix_sales_returns_id"), table_name="sales_returns")
    op.drop_table("sales_returns")
    op.drop_index(op.f("ix_sales_invoice_lines_sales_invoice_id"), table_name="sales_invoice_lines")
    op.drop_index(op.f("ix_sales_invoice_lines_product_id"), table_name="sales_invoice_lines")
    op.drop_index(op.f("ix_sales_invoice_lines_id"), table_name="sales_invoice_lines")
    op.drop_table("sales_invoice_lines")
    op.drop_index(op.f("ix_payment_receipts_payment_intent_id"), table_name="payment_receipts")
    op.drop_index(op.f("ix_payment_receipts_id"), table_name="payment_receipts")
    op.drop_table("payment_receipts")
    op.drop_index(op.f("ix_payment_attempts_payment_intent_id"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_idempotency_key"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_id"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index(op.f("ix_invoice_payments_sales_invoice_id"), table_name="invoice_payments")
    op.drop_index(op.f("ix_invoice_payments_payment_intent_id"), table_name="invoice_payments")
    op.drop_index(op.f("ix_invoice_payments_id"), table_name="invoice_payments")
    op.drop_table("invoice_payments")
    op.drop_index(op.f("ix_sales_invoices_terminal_id"), table_name="sales_invoices")
    op.drop_index(op.f("ix_sales_invoices_invoice_number"), table_name="sales_invoices")
    op.drop_index(op.f("ix_sales_invoices_invoice_barcode"), table_name="sales_invoices")
    op.drop_index(op.f("ix_sales_invoices_id"), table_name="sales_invoices")
    op.drop_index(op.f("ix_sales_invoices_cart_id"), table_name="sales_invoices")
    op.drop_index(op.f("ix_sales_invoices_branch_id"), table_name="sales_invoices")
    op.drop_table("sales_invoices")
    op.drop_index(op.f("ix_pos_cart_lines_product_id"), table_name="pos_cart_lines")
    op.drop_index(op.f("ix_pos_cart_lines_id"), table_name="pos_cart_lines")
    op.drop_index(op.f("ix_pos_cart_lines_cart_id"), table_name="pos_cart_lines")
    op.drop_table("pos_cart_lines")
    op.drop_index(op.f("ix_pos_cart_events_id"), table_name="pos_cart_events")
    op.drop_index(op.f("ix_pos_cart_events_cart_id"), table_name="pos_cart_events")
    op.drop_table("pos_cart_events")
    op.drop_index(op.f("ix_pos_cart_discounts_id"), table_name="pos_cart_discounts")
    op.drop_index(op.f("ix_pos_cart_discounts_cart_id"), table_name="pos_cart_discounts")
    op.drop_table("pos_cart_discounts")
    op.drop_index(op.f("ix_payment_intents_id"), table_name="payment_intents")
    op.drop_index(op.f("ix_payment_intents_external_id"), table_name="payment_intents")
    op.drop_index(op.f("ix_payment_intents_cart_id"), table_name="payment_intents")
    op.drop_table("payment_intents")
    op.drop_index(op.f("ix_z_reports_shift_id"), table_name="z_reports")
    op.drop_index(op.f("ix_z_reports_id"), table_name="z_reports")
    op.drop_table("z_reports")
    op.drop_index(op.f("ix_transfer_lines_transfer_batch_id"), table_name="transfer_lines")
    op.drop_index(op.f("ix_transfer_lines_product_id"), table_name="transfer_lines")
    op.drop_index(op.f("ix_transfer_lines_id"), table_name="transfer_lines")
    op.drop_table("transfer_lines")
    op.drop_index(
        op.f("ix_purchase_order_lines_purchase_order_id"), table_name="purchase_order_lines"
    )
    op.drop_index(op.f("ix_purchase_order_lines_product_id"), table_name="purchase_order_lines")
    op.drop_index(op.f("ix_purchase_order_lines_id"), table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_pos_cash_events_shift_id"), table_name="pos_cash_events")
    op.drop_index(op.f("ix_pos_cash_events_id"), table_name="pos_cash_events")
    op.drop_table("pos_cash_events")
    op.drop_index(op.f("ix_pos_carts_terminal_id"), table_name="pos_carts")
    op.drop_index(op.f("ix_pos_carts_shift_id"), table_name="pos_carts")
    op.drop_index(op.f("ix_pos_carts_id"), table_name="pos_carts")
    op.drop_index(op.f("ix_pos_carts_customer_id"), table_name="pos_carts")
    op.drop_index(op.f("ix_pos_carts_branch_id"), table_name="pos_carts")
    op.drop_table("pos_carts")
    op.drop_index(op.f("ix_goods_receipt_lines_product_id"), table_name="goods_receipt_lines")
    op.drop_index(op.f("ix_goods_receipt_lines_id"), table_name="goods_receipt_lines")
    op.drop_index(op.f("ix_goods_receipt_lines_goods_receipt_id"), table_name="goods_receipt_lines")
    op.drop_table("goods_receipt_lines")
    op.drop_index(
        op.f("ix_customer_onboarding_tokens_token_hash"), table_name="customer_onboarding_tokens"
    )
    op.drop_index(op.f("ix_customer_onboarding_tokens_id"), table_name="customer_onboarding_tokens")
    op.drop_index(
        op.f("ix_customer_onboarding_tokens_customer_id"), table_name="customer_onboarding_tokens"
    )
    op.drop_table("customer_onboarding_tokens")
    op.drop_index(op.f("ix_user_roles_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_transfer_batches_to_branch_id"), table_name="transfer_batches")
    op.drop_index(op.f("ix_transfer_batches_id"), table_name="transfer_batches")
    op.drop_index(op.f("ix_transfer_batches_from_branch_id"), table_name="transfer_batches")
    op.drop_index(op.f("ix_transfer_batches_created_by_user_id"), table_name="transfer_batches")
    op.drop_table("transfer_batches")
    op.drop_index(op.f("ix_stock_movements_product_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_branch_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_stock_levels_product_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_branch_id"), table_name="stock_levels")
    op.drop_table("stock_levels")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_purchase_orders_supplier_name"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_created_by_user_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(
        "uq_pos_shifts_terminal_open",
        table_name="pos_shifts",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_pos_shifts_terminal_id"), table_name="pos_shifts")
    op.drop_index(op.f("ix_pos_shifts_opened_by_user_id"), table_name="pos_shifts")
    op.drop_index(op.f("ix_pos_shifts_id"), table_name="pos_shifts")
    op.drop_index(op.f("ix_pos_shifts_closed_by_user_id"), table_name="pos_shifts")
    op.drop_index(op.f("ix_pos_shifts_branch_id"), table_name="pos_shifts")
    op.drop_table("pos_shifts")
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_goods_receipts_source_invoice_scan_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_invoice_number"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_created_by_user_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_branch_id"), table_name="goods_receipts")
    op.drop_table("goods_receipts")
    op.drop_index(op.f("ix_global_config_key"), table_name="global_config")
    op.drop_index(op.f("ix_global_config_id"), table_name="global_config")
    op.drop_table("global_config")
    op.drop_index(op.f("ix_customer_profiles_phone"), table_name="customer_profiles")
    op.drop_index(op.f("ix_customer_profiles_id"), table_name="customer_profiles")
    op.drop_table("customer_profiles")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_role_permissions_id"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_barcode"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_pos_terminals_terminal_code"), table_name="pos_terminals")
    op.drop_index(op.f("ix_pos_terminals_id"), table_name="pos_terminals")
    op.drop_table("pos_terminals")
    op.drop_index(op.f("ix_category_attribute_defs_id"), table_name="category_attribute_defs")
    op.drop_index(
        op.f("ix_category_attribute_defs_category_id"), table_name="category_attribute_defs"
    )
    op.drop_table("category_attribute_defs")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_invoice_scans_id"), table_name="invoice_scans")
    op.drop_table("invoice_scans")
    op.drop_index(op.f("ix_examples_id"), table_name="examples")
    op.drop_table("examples")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_branches_id"), table_name="branches")
    op.drop_index(op.f("ix_branches_code"), table_name="branches")
    op.drop_table("branches")
    # ### end Alembic commands ###
